# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=2048)),
                ('account_type', models.CharField(max_length=2048)),
                ('commodity_guid', models.CharField(max_length=32, null=True, blank=True)),
                ('commodity_scu', models.IntegerField()),
                ('non_std_scu', models.IntegerField()),
                ('parent_guid', models.CharField(max_length=32, null=True, blank=True)),
                ('code', models.CharField(max_length=2048, null=True, blank=True)),
                ('description', models.CharField(max_length=2048, null=True, blank=True)),
                ('hidden', models.IntegerField(null=True, blank=True)),
                ('placeholder', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billterms',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=2048)),
                ('refcount', models.IntegerField()),
                ('invisible', models.IntegerField()),
                ('parent', models.CharField(max_length=32, null=True, blank=True)),
                ('type', models.CharField(max_length=2048)),
                ('duedays', models.IntegerField(null=True, blank=True)),
                ('discountdays', models.IntegerField(null=True, blank=True)),
                ('discount_num', models.BigIntegerField(null=True, blank=True)),
                ('discount_denom', models.BigIntegerField(null=True, blank=True)),
                ('cutoff', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'billterms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('root_account_guid', models.CharField(max_length=32)),
                ('root_template_guid', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetAmounts',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('budget_guid', models.CharField(max_length=32)),
                ('account_guid', models.CharField(max_length=32)),
                ('period_num', models.IntegerField()),
                ('amount_num', models.BigIntegerField()),
                ('amount_denom', models.BigIntegerField()),
            ],
            options={
                'db_table': 'budget_amounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Budgets',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=2048, null=True, blank=True)),
                ('num_periods', models.IntegerField()),
            ],
            options={
                'db_table': 'budgets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Commodities',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('namespace', models.CharField(max_length=2048)),
                ('mnemonic', models.CharField(max_length=2048)),
                ('fullname', models.CharField(max_length=2048, null=True, blank=True)),
                ('cusip', models.CharField(max_length=2048, null=True, blank=True)),
                ('fraction', models.IntegerField()),
                ('quote_flag', models.IntegerField()),
                ('quote_source', models.CharField(max_length=2048, null=True, blank=True)),
                ('quote_tz', models.CharField(max_length=2048, null=True, blank=True)),
            ],
            options={
                'db_table': 'commodities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=2048)),
                ('id', models.CharField(max_length=2048)),
                ('notes', models.CharField(max_length=2048)),
                ('active', models.IntegerField()),
                ('discount_num', models.BigIntegerField()),
                ('discount_denom', models.BigIntegerField()),
                ('credit_num', models.BigIntegerField()),
                ('credit_denom', models.BigIntegerField()),
                ('currency', models.CharField(max_length=32)),
                ('tax_override', models.IntegerField()),
                ('addr_name', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr1', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr2', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr3', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr4', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_phone', models.CharField(max_length=128, null=True, blank=True)),
                ('addr_fax', models.CharField(max_length=128, null=True, blank=True)),
                ('addr_email', models.CharField(max_length=256, null=True, blank=True)),
                ('shipaddr_name', models.CharField(max_length=1024, null=True, blank=True)),
                ('shipaddr_addr1', models.CharField(max_length=1024, null=True, blank=True)),
                ('shipaddr_addr2', models.CharField(max_length=1024, null=True, blank=True)),
                ('shipaddr_addr3', models.CharField(max_length=1024, null=True, blank=True)),
                ('shipaddr_addr4', models.CharField(max_length=1024, null=True, blank=True)),
                ('shipaddr_phone', models.CharField(max_length=128, null=True, blank=True)),
                ('shipaddr_fax', models.CharField(max_length=128, null=True, blank=True)),
                ('shipaddr_email', models.CharField(max_length=256, null=True, blank=True)),
                ('terms', models.CharField(max_length=32, null=True, blank=True)),
                ('tax_included', models.IntegerField(null=True, blank=True)),
                ('taxtable', models.CharField(max_length=32, null=True, blank=True)),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('username', models.CharField(max_length=2048)),
                ('id', models.CharField(max_length=2048)),
                ('language', models.CharField(max_length=2048)),
                ('acl', models.CharField(max_length=2048)),
                ('active', models.IntegerField()),
                ('currency', models.CharField(max_length=32)),
                ('ccard_guid', models.CharField(max_length=32, null=True, blank=True)),
                ('workday_num', models.BigIntegerField()),
                ('workday_denom', models.BigIntegerField()),
                ('rate_num', models.BigIntegerField()),
                ('rate_denom', models.BigIntegerField()),
                ('addr_name', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr1', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr2', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr3', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr4', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_phone', models.CharField(max_length=128, null=True, blank=True)),
                ('addr_fax', models.CharField(max_length=128, null=True, blank=True)),
                ('addr_email', models.CharField(max_length=256, null=True, blank=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('date', models.DateTimeField()),
                ('date_entered', models.DateTimeField(null=True, blank=True)),
                ('description', models.CharField(max_length=2048, null=True, blank=True)),
                ('action', models.CharField(max_length=2048, null=True, blank=True)),
                ('notes', models.CharField(max_length=2048, null=True, blank=True)),
                ('quantity_num', models.BigIntegerField(null=True, blank=True)),
                ('quantity_denom', models.BigIntegerField(null=True, blank=True)),
                ('i_acct', models.CharField(max_length=32, null=True, blank=True)),
                ('i_price_num', models.BigIntegerField(null=True, blank=True)),
                ('i_price_denom', models.BigIntegerField(null=True, blank=True)),
                ('i_discount_num', models.BigIntegerField(null=True, blank=True)),
                ('i_discount_denom', models.BigIntegerField(null=True, blank=True)),
                ('invoice', models.CharField(max_length=32, null=True, blank=True)),
                ('i_disc_type', models.CharField(max_length=2048, null=True, blank=True)),
                ('i_disc_how', models.CharField(max_length=2048, null=True, blank=True)),
                ('i_taxable', models.IntegerField(null=True, blank=True)),
                ('i_taxincluded', models.IntegerField(null=True, blank=True)),
                ('i_taxtable', models.CharField(max_length=32, null=True, blank=True)),
                ('b_acct', models.CharField(max_length=32, null=True, blank=True)),
                ('b_price_num', models.BigIntegerField(null=True, blank=True)),
                ('b_price_denom', models.BigIntegerField(null=True, blank=True)),
                ('bill', models.CharField(max_length=32, null=True, blank=True)),
                ('b_taxable', models.IntegerField(null=True, blank=True)),
                ('b_taxincluded', models.IntegerField(null=True, blank=True)),
                ('b_taxtable', models.CharField(max_length=32, null=True, blank=True)),
                ('b_paytype', models.IntegerField(null=True, blank=True)),
                ('billable', models.IntegerField(null=True, blank=True)),
                ('billto_type', models.IntegerField(null=True, blank=True)),
                ('billto_guid', models.CharField(max_length=32, null=True, blank=True)),
                ('order_guid', models.CharField(max_length=32, null=True, blank=True)),
            ],
            options={
                'db_table': 'entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gnclock',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('hostname', models.CharField(max_length=255, null=True, db_column='Hostname', blank=True)),
                ('pid', models.IntegerField(null=True, db_column='PID', blank=True)),
            ],
            options={
                'db_table': 'gnclock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('id', models.CharField(max_length=2048)),
                ('date_opened', models.DateTimeField(null=True, blank=True)),
                ('date_posted', models.DateTimeField(null=True, blank=True)),
                ('notes', models.CharField(max_length=2048)),
                ('active', models.IntegerField()),
                ('currency', models.CharField(max_length=32)),
                ('owner_type', models.IntegerField(null=True, blank=True)),
                ('owner_guid', models.CharField(max_length=32, null=True, blank=True)),
                ('terms', models.CharField(max_length=32, null=True, blank=True)),
                ('billing_id', models.CharField(max_length=2048, null=True, blank=True)),
                ('post_txn', models.CharField(max_length=32, null=True, blank=True)),
                ('post_lot', models.CharField(max_length=32, null=True, blank=True)),
                ('post_acc', models.CharField(max_length=32, null=True, blank=True)),
                ('billto_type', models.IntegerField(null=True, blank=True)),
                ('billto_guid', models.CharField(max_length=32, null=True, blank=True)),
                ('charge_amt_num', models.BigIntegerField(null=True, blank=True)),
                ('charge_amt_denom', models.BigIntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('id', models.CharField(max_length=2048)),
                ('name', models.CharField(max_length=2048)),
                ('reference', models.CharField(max_length=2048)),
                ('active', models.IntegerField()),
                ('owner_type', models.IntegerField(null=True, blank=True)),
                ('owner_guid', models.CharField(max_length=32, null=True, blank=True)),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('account_guid', models.CharField(max_length=32, null=True, blank=True)),
                ('is_closed', models.IntegerField()),
            ],
            options={
                'db_table': 'lots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('id', models.CharField(max_length=2048)),
                ('notes', models.CharField(max_length=2048)),
                ('reference', models.CharField(max_length=2048)),
                ('active', models.IntegerField()),
                ('date_opened', models.DateTimeField()),
                ('date_closed', models.DateTimeField()),
                ('owner_type', models.IntegerField()),
                ('owner_guid', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('commodity_guid', models.CharField(max_length=32)),
                ('currency_guid', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('source', models.CharField(max_length=2048, null=True, blank=True)),
                ('type', models.CharField(max_length=2048, null=True, blank=True)),
                ('value_num', models.BigIntegerField()),
                ('value_denom', models.BigIntegerField()),
            ],
            options={
                'db_table': 'prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurrences',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('obj_guid', models.CharField(max_length=32)),
                ('recurrence_mult', models.IntegerField()),
                ('recurrence_period_type', models.CharField(max_length=2048)),
                ('recurrence_period_start', models.DateField()),
                ('recurrence_weekend_adjust', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'recurrences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedxactions',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=2048, null=True, blank=True)),
                ('enabled', models.IntegerField()),
                ('start_date', models.DateField(null=True, blank=True)),
                ('end_date', models.DateField(null=True, blank=True)),
                ('last_occur', models.DateField(null=True, blank=True)),
                ('num_occur', models.IntegerField()),
                ('rem_occur', models.IntegerField()),
                ('auto_create', models.IntegerField()),
                ('auto_notify', models.IntegerField()),
                ('adv_creation', models.IntegerField()),
                ('adv_notify', models.IntegerField()),
                ('instance_count', models.IntegerField()),
                ('template_act_guid', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'schedxactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('obj_guid', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=4096)),
                ('slot_type', models.IntegerField()),
                ('int64_val', models.BigIntegerField(null=True, blank=True)),
                ('string_val', models.CharField(max_length=4096, null=True, blank=True)),
                ('double_val', models.FloatField(null=True, blank=True)),
                ('timespec_val', models.DateTimeField(null=True, blank=True)),
                ('guid_val', models.CharField(max_length=32, null=True, blank=True)),
                ('numeric_val_num', models.BigIntegerField(null=True, blank=True)),
                ('numeric_val_denom', models.BigIntegerField(null=True, blank=True)),
                ('gdate_val', models.DateField(null=True, blank=True)),
            ],
            options={
                'db_table': 'slots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Splits',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('tx_guid', models.CharField(max_length=32)),
                ('account_guid', models.CharField(max_length=32)),
                ('memo', models.CharField(max_length=2048)),
                ('action', models.CharField(max_length=2048)),
                ('reconcile_state', models.CharField(max_length=1)),
                ('reconcile_date', models.DateTimeField(null=True, blank=True)),
                ('value_num', models.BigIntegerField()),
                ('value_denom', models.BigIntegerField()),
                ('quantity_num', models.BigIntegerField()),
                ('quantity_denom', models.BigIntegerField()),
                ('lot_guid', models.CharField(max_length=32, null=True, blank=True)),
            ],
            options={
                'db_table': 'splits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaxtableEntries',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('taxtable', models.CharField(max_length=32)),
                ('account', models.CharField(max_length=32)),
                ('amount_num', models.BigIntegerField()),
                ('amount_denom', models.BigIntegerField()),
                ('type', models.IntegerField()),
            ],
            options={
                'db_table': 'taxtable_entries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxtables',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=50)),
                ('refcount', models.BigIntegerField()),
                ('invisible', models.IntegerField()),
                ('parent', models.CharField(max_length=32, null=True, blank=True)),
            ],
            options={
                'db_table': 'taxtables',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('currency_guid', models.CharField(max_length=32)),
                ('num', models.CharField(max_length=2048)),
                ('post_date', models.DateTimeField(null=True, blank=True)),
                ('enter_date', models.DateTimeField(null=True, blank=True)),
                ('description', models.CharField(max_length=2048, null=True, blank=True)),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('guid', models.CharField(max_length=32, serialize=False, primary_key=True)),
                ('name', models.CharField(max_length=2048)),
                ('id', models.CharField(max_length=2048)),
                ('notes', models.CharField(max_length=2048)),
                ('currency', models.CharField(max_length=32)),
                ('active', models.IntegerField()),
                ('tax_override', models.IntegerField()),
                ('addr_name', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr1', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr2', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr3', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_addr4', models.CharField(max_length=1024, null=True, blank=True)),
                ('addr_phone', models.CharField(max_length=128, null=True, blank=True)),
                ('addr_fax', models.CharField(max_length=128, null=True, blank=True)),
                ('addr_email', models.CharField(max_length=256, null=True, blank=True)),
                ('terms', models.CharField(max_length=32, null=True, blank=True)),
                ('tax_inc', models.CharField(max_length=2048, null=True, blank=True)),
                ('tax_table', models.CharField(max_length=32, null=True, blank=True)),
            ],
            options={
                'db_table': 'vendors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('table_name', models.CharField(max_length=50, serialize=False, primary_key=True)),
                ('table_version', models.IntegerField()),
            ],
            options={
                'db_table': 'versions',
                'managed': False,
            },
        ),
    ]
